# Site Specific Configuration
name: Mathemattical Art and Beauty
description: To accentuate the beauty of nature through mathematics
url: https://hackgptdeveloper.github.io
author: Peter Teoh

# Keywords
keywords: ['mathematics', 'AI', 'beauty', 'art']

# Styling
sass:
  sass_dir: _sass
  style: expanded # compact, expanded or compressed

# Paginate
pagination:
  enabled: true
  # Value set low for demonstration purposes
  per_page: 3
  sort_field: 'date'
  sort_reverse: true

# Category Paginating
autopages:
  enabled: true
  categories:
    title: 'Posts in category :cat'
    permalink: '/category/:cat'
    silent: false

# Exclusions
exclude: [ 'README.md', 'COPYING' ]

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-seo-tag

